spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db1?useSSL=false
    username: root
    password: 1234

logging:
  level:
    com.yonyou.controller.IndexController: error

