## 设置启用环境
spring:
  profiles:
    active: development

---
server:
  port: 80
spring:
  profiles: development

---
server:
  port: 81
spring:
  profiles: production

---

server:
  port: 82
spring:
  profiles: test

